/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author alvis
 */
public class ifrmPlanillas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmPlanillas
     */
    public ifrmPlanillas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        lblPlanilla = new javax.swing.JLabel();
        panPlanillas = new javax.swing.JPanel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, 962, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Empleado", "Puesto", "Salario base", "Anualidad", "Escalafon", "Dedicacion Exc", "Participacion", "Reg. Pension", "CCSS", "Poliza de vida", "Colegio prof."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 60, 920, 420));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 960, -1));

        lblPlanilla.setFont(new java.awt.Font("Hack Nerd Font", 3, 24)); // NOI18N
        lblPlanilla.setText("Planillas");
        getContentPane().add(lblPlanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 130, 30));

        panPlanillas.setPreferredSize(new java.awt.Dimension(1600, 800));

        javax.swing.GroupLayout panPlanillasLayout = new javax.swing.GroupLayout(panPlanillas);
        panPlanillas.setLayout(panPlanillasLayout);
        panPlanillasLayout.setHorizontalGroup(
            panPlanillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panPlanillasLayout.setVerticalGroup(
            panPlanillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(panPlanillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1000, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPlanilla;
    private javax.swing.JPanel panPlanillas;
    // End of variables declaration//GEN-END:variables
}
